version: '3'

services:

  app:
    build:
      context: node
    container_name: app
    networks:
      - nodenet
    volumes:
      - ./node:/usr/src/app         
    command: ["/usr/bin/wait-for", "db:3306", "-t 40", "--", "node", "index.js"]
    tty: true      
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx      
    image: eleyoliveira/nginx:node
    container_name: nginx
    networks:
      - nodenet
    ports:
      - "8080:8080"
    depends_on:
      - app

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ../mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - nodenet

networks:
  nodenet:
    driver: bridge

  